### ISSUE TITLE
Creación del servicio para listar el catálogo de álbumes

### ISSUE THREAD

**Issue by haibergalindouniandes** [shiomar-salazar/MISW4203-202312-TSDC-Vinilos#10]
Esta actividad consistirá en implementar el servicio que consulta el catálogo de álbumes a través del consumo del recurso Get All Albums del API Vynils

**Comment by shiomar-salazar** [comment]
Cerrado con https://github.com/shiomar-salazar/MISW4203-202312-TSDC-Vinilos/pull/44
