### ISSUE TITLE
Creación de la ventana Detalle del Album

### ISSUE THREAD

**Issue by haibergalindouniandes** [shiomar-salazar/MISW4203-202312-TSDC-Vinilos#13]
Esta actividad consistirá en implementar la interfaz gráfica correspondiente a la ventana del álbum seleccionado, que contendrá toda la información referente a nombre, caratula miniatura, fecha de lanzamiento, genero, disquera, artista y tracks

**Comment by shiomar-salazar** [comment]
Se cierra con 
https://github.com/shiomar-salazar/MISW4203-202312-TSDC-Vinilos/pull/59
