### ISSUE TITLE
Creación del servicio para consultar el detalle del Álbum

### ISSUE THREAD

**Issue by haibergalindouniandes** [shiomar-salazar/MISW4203-202312-TSDC-Vinilos#14]
Esta actividad consistirá en implementar el servicio que consulta el detalle del álbum a través del consumo del recurso Get Album By Id del API Vynils

**Comment by shiomar-salazar** [comment]
Se termina con https://github.com/shiomar-salazar/MISW4203-202312-TSDC-Vinilos/pull/58
