### ISSUE TITLE
Integración del servicio de consulta del detalle del álbum con la ventana del detalle

### ISSUE THREAD

**Issue by haibergalindouniandes** [shiomar-salazar/MISW4203-202312-TSDC-Vinilos#15]
Esta actividad consistirá en integrar la información retornada del servicio de consulta de detalle de información del álbum con la ventana de Detalle y se implementará la lógica necesaria para generar la lista deslizable de álbumes, visualización de la información del álbum, caratula del álbum en miniatura y transiciones entre ventanas

**Comment by shiomar-salazar** [comment]
Cerrado con https://github.com/shiomar-salazar/MISW4203-202312-TSDC-Vinilos/pull/62
