### ISSUE TITLE
Creación del servicio para consultar el listado de Coleccionistas

### ISSUE THREAD

**Issue by haibergalindouniandes** [shiomar-salazar/MISW4203-202312-TSDC-Vinilos#19]
Esta actividad realizara la implementación del API que permitira consultar el listado de conleccionistas registrados en la aplicacion

**Comment by shiomar-salazar** [comment]
Se cierra con https://github.com/shiomar-salazar/MISW4203-202312-TSDC-Vinilos/pull/55
