### ISSUE TITLE
Creación de la navegación de Listado de Coleccionistas

### ISSUE THREAD

**Issue by haibergalindouniandes** [shiomar-salazar/MISW4203-202312-TSDC-Vinilos#21]
Se crearan la navegación entre pantallas que permita llegar a la opción de ver el listado de coleccionistas adicional, se creara la navegaciión para volver al menu principal

**Comment by shiomar-salazar** [comment]
Historia se cierra sin cambios, ya que esta navieegacion ya esta desde el Sprint1
