### ISSUE TITLE
Creación de la ventana Detalle del Coleccionista

### ISSUE THREAD

**Issue by haibergalindouniandes** [shiomar-salazar/MISW4203-202312-TSDC-Vinilos#23]
Esta actididad consist en en creación de la pantalla del detalle del coleccionista seleccionado mostrando la información de Nombre, Telefono, Email

**Comment by shiomar-salazar** [comment]
Se cierra con https://github.com/shiomar-salazar/MISW4203-202312-TSDC-Vinilos/pull/73
