### ISSUE TITLE
Creación pruebas E2E de la ventana Detalle de coleccionista

### ISSUE THREAD

**Issue by haibergalindouniandes** [shiomar-salazar/MISW4203-202312-TSDC-Vinilos#24]
Esta actividad consiste en la creación del set de pruebas E2E que permita garantizar el funcionamiento del detalle de los coleccionistas

**Comment by shiomar-salazar** [comment]
Se cierra con https://github.com/shiomar-salazar/MISW4203-202312-TSDC-Vinilos/pull/77
