### ISSUE TITLE
Integración del servicio de consulta de artista con la ventana de detalle de artista

### ISSUE THREAD

**Issue by shiomar-salazar** [shiomar-salazar/MISW4203-202312-TSDC-Vinilos#33]
Integracion de la información que retorna el servicio de consulta de un artista con la ventana de detalle e implementacion de la lógica necesaria para generar la lista deslizable con la informacion relevante del artista, visualización de foto y nombre del artista, biografia, albumes principales y premios asociados al artista.

**Comment by haibergalindouniandes** [comment]
Se realiza la implementacion de codigo relacionado a integrar la pantalla de Detalle Artistas con el servidio de consulta.

Se adjunta PR https://github.com/shiomar-salazar/MISW4203-202312-TSDC-Vinilos/pull/60
