### ISSUE TITLE
Integrar navegación de Comentarios con vistas existentes.

### ISSUE THREAD

**Issue by shiomar-salazar** [shiomar-salazar/MISW4203-202312-TSDC-Vinilos#7]
Se integrará la información retornada del servicio de creación de comentarios con la ventana de Detalle y se implementará la lógica necesaria para generar la lista deslizable de comeentarios, valoración de cada comentario y transiciones entre ventanas.

**Comment by haibergalindouniandes** [comment]
Se debera realizar la HU

**Comment by shiomar-salazar** [comment]
Se cierra con https://github.com/shiomar-salazar/MISW4203-202312-TSDC-Vinilos/pull/74
