### ISSUE TITLE
Faltan validaciones de Campos antes de Crear Album y Comentario

### ISSUE THREAD

**Issue by shiomar-salazar** [shiomar-salazar/MISW4203-202312-TSDC-Vinilos#80]
## Firebase reaper detecto el siguiente error:
![image](https://github.com/shiomar-salazar/MISW4203-202312-TSDC-Vinilos/assets/111320185/37a28f01-e017-41f6-8a88-9835a2c9bd4c)

## Pasos para la reproduccion:
1. Ejecutar la aplicacion en dispositivo fisico desde Android Studio
1. Una vez cargada la Aplicacion hacer click en el Boton "Menu Coleccionista"
1. Hacer click en el Boton "Catalogo de Álbumes"
1. Esperar a se se cargue la informacion del Listado de Albunes
1. La ventana de Listado de Álbumes deber ser visible.
1. Hacer click en el boton flotante (+)
2. Llenar 1 o ninguno de los campos.
3. Dar click en aceptar.

## Evidencia de la repoduccion:
![image](https://github.com/shiomar-salazar/MISW4203-202312-TSDC-Vinilos/assets/111320185/cf51d34e-64f5-4e79-b08d-68a700c2b775)

## Comportamiento esperado:
Al darle encima del boton Guardar se debe validar que esten diligenciados todos los campos para Crear Album o Crear Comentario llenos.

## Comportamiento obtenido:
El boton aceptar esta siempre esta habilitado.

## Video del issue

https://github.com/shiomar-salazar/MISW4203-202312-TSDC-Vinilos/assets/111320185/67d613a6-1cca-42d7-a1c9-e37f3334b993

**Comment by haibergalindouniandes** [comment]
## Descripción de la solución:
Se implementa a nivel de código de la app, la validación de campos tanto en la vista de creación de album nuevo, como en la vista de creación de comentarios.

### Clase AlbumCreateFragment

![image](https://github.com/shiomar-salazar/MISW4203-202312-TSDC-Vinilos/assets/110913673/9567470a-b186-4f78-a0ff-f64bcd090b79)

### Clase CommentCreateFragment
![image](https://github.com/shiomar-salazar/MISW4203-202312-TSDC-Vinilos/assets/110913673/910c7562-94aa-4bf8-a786-e7678d9babad)

## Comportamiento actual:
Al dar en el botón Guardar se validan que todos los campos sean debidamente diligenciados. Esto aplica tanto en la vista de creación de álbum nuevo como la vista de creación de comentarios.

## Evidencias de la solución:

https://github.com/shiomar-salazar/MISW4203-202312-TSDC-Vinilos/assets/110913673/698535d4-4977-4bd3-a783-c971c8f10eb3

**Evidencia correción Bug Creación Comentrario:**

https://github.com/shiomar-salazar/MISW4203-202312-TSDC-Vinilos/assets/110913673/50066db2-71a6-4561-8db4-d05ed520d760
